eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/
server:
  port: 8766
spring:
  application:
    name: server-web
  zipkin:
    base-url: http://127.0.0.1:9411/
  sleuth:
    sampler:
      probability: 1.0
feign:
  hystrix:
    enabled: true

