server:
  port: 8761

spring:
  profiles: peer1
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer2:8762/eureka/