eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer1:8761/eureka/
server:
  port: 81

spring:
  application:
    name: server-oauth2-router
  zipkin:
    base-url: http://127.0.0.1:9411/
    sleuth:
      sampler:
        probability: 1.0

zuul:
  ignored-services:  '*'
  prefix: /api
  routes:
    server-cas-route:
      path: /cas/**
      serviceId: server-cas
      strip-prefix: true
    server-web-route:
      path: /web/**
      serviceId: server-web
      strip-prefix: true
    server-auth-route:
      path: /oauth/**
      sensitive-headers:
      serviceId: SERVER-OAUTH2
      strip-prefix: false
    server-user-route:
      path: /user/**
      serviceId: server-user
      strip-prifix: true

security:
  oauth2:
    client:
      access-token-uri: http://localhost:8763/oauth/token
      user-authorization-uri: http://localhost:8763/oauth/authorize
      client-id: client1
      client-secret: client1
    resource:
      jwt:
        key-uri: http://localhost:8763/oauth/token_key
        key-value: sdjhakdhajdklsl;o653632